config/routes.rb
Rails.application.routes.draw do
  # get 'personas/index'
  # get 'personas/show'
  # get 'personas/edit'
  # get 'personas/new'
  # get 'viviendas/index'
  # get 'viviendas/show'
  # get 'viviendas/edit'
  # get 'viviendas/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :personas
  resources :viviendas

  get 'main_page/index',as: "main_page"


  root 'main_page#index'









end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
class Persona < ApplicationRecord
    validates :email, presence:true,uniqueness:true
    validates :nombre, presence:true
    validates :apellido, presence:true
    validates :fecha, presence:true
    belongs_to :vivienda
end

app/models/vivienda.rb
class Vivienda < ApplicationRecord
    validates :tipo_vivienda, presence:true
    validates :ciudad, presence:true
    validates :calle, presence:true
    validates :numero, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController

def index
end

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  def index
    @personas=Persona.all
  end

  def show
  end

  def edit
    @persona=Persona.find(params[:id])
  end

  def update
    @persona=Persona.find(params[:id])
    if @persona.update(
      params
      .require(:persona)
      .permit(:nombre, :apellido, :email, :fecha, :vivienda_id)
    )
      redirect_to personas_path
      flash[:success]="Persona actualizada"
    else
      render :edit
    end
                
  end


  def new
    @persona=Persona.new
  end

  def create
    @persona=Persona.new(params
                              .require(:persona)
                              .permit(:nombre, :apellido,
                                :email, :fecha, :vivienda_id)
                            )
    if @persona.save
      redirect_to personas_path
    else
      render :new

    end
  end
end

app/controllers/viviendas_controller.rb
class ViviendasController < ApplicationController
  def index
    @viviendas=Vivienda.all
  end

  def show
    @vivienda=Vivienda.find(params[:id])
  end

  def edit
    @vivienda=Vivienda.find(params[:id])
  end

  def update
    @vivienda=Vivienda.find(params[:id])
    if @vivienda.update(
      params
      .require(:vivienda)
      .permit(:tipo_vivienda, :ciudad, :calle, :numero, :piso, :depto)
    )
      redirect_to viviendas_path
      flash[:success]="Vivienda actualizada"
    else
      render :edit
    end
                
  end


  def new
    @vivienda=Vivienda.new
  end

  def create
    @vivienda=Vivienda
    .new(params
        .require(:vivienda)
        .permit(:tipo_vivienda, :ciudad, :calle, :numero, :piso, :depto))
    if @vivienda.save
      redirect_to viviendas_path
    else
      render :new

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/viviendas_helper.rb
module ViviendasHelper
end

app/views/layouts/_header.html.erb
<header>
    
    <nav class="navbar p-0 navbar-expand navbar-dark bg-dark">        
      <div class="container">
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "vivienda.png",class: "navbar-brand" %>
            <p class='navbar-text'>BASE DE DATOS DE VIVIENDAS</p>
          <% end %>
      </div>
    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Database de viviendas</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/header'%>
  <div class="container"> 
  
    <% if flash[:notice] %>
      <div class="alert alert-info"> <%= flash[:notice] %> </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/main_page/index.html.erb
<h1> Bienvenido a Un laboratorio dificil </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nueva vivienda", new_vivienda_path %></li>
  <li> <%= link_to "Listado de Personas", personas_path %></li>  
  <li> <%= link_to "Listado de Viviendas", viviendas_path %></li>  
  <li> <%= link_to "Futura ayuda", nil %></li> 
</ul>

app/views/personas/_form.html.erb
<div class="container mt-3 mb-2">
    <%= form_for(@persona) do |f|%>
    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese nombre y apellido</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">

            <%=f.text_field :nombre,
                placeholder: "Ingrese nombre",
                required: true
                %>
        </div>
        <div class="p-2">
        <%=f.text_field :apellido,
            placeholder: "Ingrese apellido",
            required: true
            %>
        </div>
    </div>  
    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese direccion de correo</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">

            <%=f.text_field :email,
                placeholder: "Ingrese email",
                required: true
                %>
        </div>
    </div>  
    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese fecha de nacimiento</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">

            <%= f.date_field :fecha,
                placeholder: "Ingrese fecha de nacimiento",
                required: true%>
        </div>
    </div>

    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese vivienda valida</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">
            <%= collection_select(:persona,
            :vivienda_id,
            Vivienda.all,
            :id,
            :id,
            {prompt: "Seleccione una"},
            { class: 'form-control'}) %>
        </div>
    </div>

    <div class="row mb-1 mt-5 px-3">
        <%= f.submit "Guardar persona", class:"btn btn-success btn-lg"%>
    </div>
    <%end%>
</div>
<!--
<%= text_area_tag(:message, "Hi, nice site", size: "24x6") %>
<%= password_field_tag(:password) %>
<%= hidden_field_tag(:parent_id, "5") %>
<%= search_field(:user, :name) %>
<%= telephone_field(:user, :phone) %>
<%= date_field(:user, :born_on) %>
<%= datetime_local_field(:user, :graduation_day) %>
<%= month_field(:user, :birthday_month) %>
<%= week_field(:user, :birthday_week) %>
<%= url_field(:user, :homepage) %>
<%= email_field(:user, :address) %>
<%= color_field(:user, :favorite_color) %>
<%= time_field(:task, :started_at) %>
<%= number_field(:product, :price, in: 1.0..20.0, step: 0.5) %>
<%= range_field(:product, :discount, in: 1..100) %>

-->

app/views/personas/edit.html.erb
<div class="container">
<div class="row container mt-5 mb-3">
    <h1 class="bold">Editar a <%=@persona.nombre%></h1>
</div>

<%=render 'form'%>
</div>

app/views/personas/index.html.erb
<div class="container-fluid mt-5">
<div class="container mt-3 mb-4">
<div class="row">
	<h1 class="col"> Listado de Personas </h1>
	<%= link_to "Crear", new_persona_path, class: 'btn btn-primary btn-lg m-2' %>
</div>
</div>


<div class="container">

<table class="table">

	<tr>
		<th> Nombre y apellido </th>
		<th> Email </th>
		<th> Fecha de ?? </th>
		<th> Vivienda </th>
        <th> Opciones</th>
	</tr>


	<% @personas.each do |persona| %>
		<tr>
			<td> <%= link_to(
				persona.apellido+" " + persona.nombre,
                persona)
                 %>
            </td>

			<td> <%= persona.email %> </td>

			<td> <%= persona.fecha %> </td>

            <td> <%= link_to(
				"N°: " + persona.vivienda.id.to_s,
                persona.vivienda)%>
            </td>

			<td>
				<%= link_to "Editar", edit_persona_path(persona), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar",
				 persona,
				  method: :delete,
				  data:{confirm: "Segurx?"},
				  class: 'btn btn-danger btn-sm'
				  %>
			</td>

		</tr>
	<% end %>

	<% if @personas.size == 0 %>
		<tr> <td colspan="3"> No hay personas en la base de datos </td> </tr>
	<% end %>

</table>

</div>


</div>

app/views/personas/new.html.erb
<div class="container">
<div class="row container mt-5 mb-3">
    <h1 class="bold">Agregar una persona a la base de datos</h1>
</div>

<%=render 'form'%>


</div>

app/views/personas/show.html.erb
<h1>Personas#show</h1>
<p>Find me in app/views/personas/show.html.erb</p>

app/views/viviendas/_form.html.erb
<div class="container mt-3 mb-2">
    <%= form_for(@vivienda) do |f|%>
    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese Tipo de vivienda</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">

            <%=f.text_field :tipo_vivienda,
                placeholder: "Ingrese tipo",
                required: true
                %>
        </div>
    </div>  
    <div class="row mb-1 mt-5">
        <p class=h5>Ingrese direccion</p>
    </div>
    <div class="d-flex flex-row">
        <div class="p-2">

            <%=f.text_field :ciudad,
                placeholder: "Ciudad",
                required: true
                %>
        </div>
        <div class="p-2">

            <%=f.text_field :calle,
                placeholder: "Calle",
                required: true
                %>
        </div>
        <div class="p-2">

            <%=f.text_field :numero,
                placeholder: "Numero",
                required: true
                %>
        </div>
        <div class="p-2">

            <%=f.text_field :piso,
                placeholder: "Piso",
                required: true
                %>
        </div>
        <div class="p-2">

            <%=f.text_field :depto,
                placeholder: "Depto",
                required: true
                %>
        </div>
    </div>  
    
    <div class="row mb-1 mt-5 px-3">
        <%= f.submit "Guardar persona", class:"btn btn-success btn-lg"%>
    </div>
    <%end%>
</div>
<!--
<%= text_area_tag(:message, "Hi, nice site", size: "24x6") %>
<%= password_field_tag(:password) %>
<%= hidden_field_tag(:parent_id, "5") %>
<%= search_field(:user, :name) %>
<%= telephone_field(:user, :phone) %>
<%= date_field(:user, :born_on) %>
<%= datetime_local_field(:user, :graduation_day) %>
<%= month_field(:user, :birthday_month) %>
<%= week_field(:user, :birthday_week) %>
<%= url_field(:user, :homepage) %>
<%= email_field(:user, :address) %>
<%= color_field(:user, :favorite_color) %>
<%= time_field(:task, :started_at) %>
<%= number_field(:product, :price, in: 1.0..20.0, step: 0.5) %>
<%= range_field(:product, :discount, in: 1..100) %>

-->

app/views/viviendas/edit.html.erb
<div class="container">
<div class="row container mt-5 mb-3">
    <h1 class="bold">Editar a <%="Vivienda numero: " + @vivienda.id.to_s%></h1>
</div>

<%=render 'form'%>
</div>

app/views/viviendas/index.html.erb
<div class="container-fluid mt-5">
<div class="container mt-3 mb-4">
<div class="row">
	<h1 class="col"> Listado de Viviendas </h1>
	<%= link_to "Crear", new_vivienda_path, class: 'btn btn-primary btn-lg m-2' %>
</div>
</div>


<div class="container">

<table class="table">

	<tr>
		<th> Tipo de vivienda </th>
		<th> Ciudad </th>
		<th> Calle </th>
		<th> Numero </th>
        <th> Piso</th>
        <th> Depto</th>
	</tr>


	<% @viviendas.each do |vivienda| %>
		<tr>
			<td> <%= link_to(
				"Vivienda no: " + vivienda.id.to_s + ", " + vivienda.tipo_vivienda,
                vivienda)
                 %>
            </td>

			<td> <%= vivienda.ciudad %> </td>

			<td> <%= vivienda.calle %> </td>

            <td> <%= vivienda.numero %> </td>

            <td> <%= vivienda.piso %> </td>

            <td> <%= vivienda.depto %> </td>

			<td>
				<%= link_to "Editar", edit_vivienda_path(vivienda), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar",
				 vivienda,
				  method: :delete,
				  data:{confirm: "Segurx?"},
				  class: 'btn btn-danger btn-sm'
				  %>
			</td>

		</tr>
	<% end %>

	<% if @viviendas.size == 0 %>
		<tr> <td colspan="3"> No hay viviendas en la base de datos </td> </tr>
	<% end %>

</table>

</div>


</div>

app/views/viviendas/new.html.erb
<div class="container">
<div class="row container mt-5 mb-3">
    <h1 class="bold">Agregar una vivienda a la base de datos</h1>
</div>

<%=render 'form'%>


</div>

app/views/viviendas/show.html.erb
<h1>Viviendas#show</h1>
<p>Find me in app/views/viviendas/show.html.erb</p>
<%=image_tag @vivienda[:image_url],class:"img-fluid"%>